WIN_TITLE = "ConnectCztery"
COL = 7
ROW = 6
WIN_X = 700
WIN_Y = 700 * ROW/COL
RADIUS = 3/4 * WIN_X / (2*COL)
BASE = WIN_Y/18 # Height of the part with numbers
background_color = "white"
TL = 4 # Target Length
debug = True
